### ISSUE TITLE
ViewFinderView这个类219行的方法，计算文本的地方没有判断，导致文本为英文的时候会出现错位

### ISSUE THREAD

**Issue by hloong** [XuDaojie/QRCode-Android#17]
下面这个方法里面的drawText，单纯的frame.centerX() - text.length() * 36 / 2 这样计算有问题，如果文字是英文的，就会导致frame.centerX()小于text.length() * 36 / 2  ；
应该改成frame.centerX() - paint.measureText(text) / 2；这样才不会因为多语言出现错位不居中

` private void drawText(Canvas canvas, Rect frame) {
        if (cameraPermission == PackageManager.PERMISSION_GRANTED) {
            paint.setColor(hintColor);
            paint.setTextSize(36);
            String text = hint;
            canvas.drawText(hint, frame.centerX() - text.length() * 36 / 2, frame.bottom + 35 + 20, paint);
        } else {
            paint.setColor(errorHintColor);
            paint.setTextSize(36);
            String text = errorHint;
            canvas.drawText(errorHint, frame.centerX() - text.length() * 36 / 2, frame.bottom + 35 + 20, paint);
        }
    }`

**Comment by XuDaojie** [comment]
别用我这个库啊，老早不管了，推荐你用这个[BGAQRCode-Android](https://github.com/bingoogolapple/BGAQRCode-Android)

**Comment by hloong** [comment]
> 别用我这个库啊，老早不管了，推荐你用这个[BGAQRCode-Android](https://github.com/bingoogolapple/BGAQRCode-Android)

好吧，那我关掉issue了
